[project]
authors = ["ogkristi <139138898+ogkristi@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gmb302"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
matplotlib = ">=3.10.8,<4"
ipywidgets = ">=8.1.8,<9"

[pypi-dependencies]
opencv-python-headless = ">=4.11.0.86, <5"
