[project]
authors = ["ogkristi <139138898+ogkristi@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gmb302"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
